//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.example.ui;

import android.app.Activity;
import android.app.Fragment;
import android.content.Context;
import android.content.Intent;
import android.graphics.Matrix;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ImageView;
import com.example.ui.R.id;
import com.example.ui.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MatrixActivity_
    extends MatrixActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.matrix);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MatrixActivity_.IntentBuilder_ intent(Context context) {
        return new MatrixActivity_.IntentBuilder_(context);
    }

    public static MatrixActivity_.IntentBuilder_ intent(Fragment fragment) {
        return new MatrixActivity_.IntentBuilder_(fragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btn1 = ((Button) hasViews.findViewById(id.btn1));
        iv1 = ((ImageView) hasViews.findViewById(id.iv1));
        iv2 = ((ImageView) hasViews.findViewById(id.iv2));
        btn3 = ((Button) hasViews.findViewById(id.btn3));
        btn5 = ((Button) hasViews.findViewById(id.btn5));
        btn4 = ((Button) hasViews.findViewById(id.btn4));
        btn2 = ((Button) hasViews.findViewById(id.btn2));
        {
            View view = hasViews.findViewById(id.btn3);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MatrixActivity_.this.btn3();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btn5);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MatrixActivity_.this.btn5();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btn1);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MatrixActivity_.this.btn1();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btn4);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MatrixActivity_.this.btn4();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btn2);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MatrixActivity_.this.btn2();
                    }

                }
                );
            }
        }
        afterViewProcess();
    }

    @Override
    public void showToast(final Matrix matrix) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MatrixActivity_.super.showToast(matrix);
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragment_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MatrixActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, MatrixActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MatrixActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragment_!= null) {
                fragment_.startActivityForResult(intent_, requestCode);
            } else {
                if (context_ instanceof Activity) {
                    ((Activity) context_).startActivityForResult(intent_, requestCode);
                } else {
                    context_.startActivity(intent_);
                }
            }
        }

    }

}
